### ISSUE TITLE
Please upload it to Mozilla's addons and Chrome's Webstore.

### ISSUE THREAD

**Issue by murnur19** [Dither/autopatchwork-mod#11]
Please upload it to Mozilla's addons and Chrome's Webstore.  I believe many will appreciate it.
I've been tried many extensions, auto pager, autopagerize, page zipper. and many of them. I ended up with autopagerize userscripts version for years.
And I just discovered your works yesterday. It's working great in Firefox, Chrome, Opera and Vivaldi.
Thank you very much.

**Comment by Dither** [comment]
I thought about it previously and decided not to. Maybe at some point in the future...

**Comment by shiro2peppers** [comment]
I also want to ask from you.
I tried to install it manually into Vivaldi, but I do not know the reason but I could not install it because I got a manifest error.
Or I want some means to install from this page. It is difficult manually.

**Comment by Dither** [comment]
I didn't test in in Vivaldi but It's Chrome-based so should work theoretically. Try removing lines that show you errors from the manifest.

**Comment by shiro2peppers** [comment]
I tray folder install.
この拡張機能をインストールしようとしたときに、次の警告がありました。
Unrecognized manifest key 'applications'.
Unrecognized manifest key 'developer'.

**Comment by Dither** [comment]
@shiro2peppers let us use [separate issue](https://github.com/Dither/autopatchwork-mod/issues/13). The problem is not related to this one. I will move my answers there.
