### ISSUE TITLE
How to add and use it?

### ISSUE THREAD

**Issue by hien4990** [Dither/autopatchwork-mod#12]
Please tell me how to add to browser and use it? I'm using Firefox

**Comment by Dither** [comment]
It's not very easy if you aren't developer:
You need to unblock unsigned extensions and/or patch FF Aurora to load unpacked extensions. First can be done by adding the js [files](https://gist.github.com/Dither/65373d145c63927b420d33fc0e39cd9b) to FF folder (you only need first 8 lines from the `config.js` then `config-prefs.js`). 
The manual loading part can be enabled either by using latest Aurora build with the option enabled or patching corresponding files from `browser\omni.ja` archive with [this](https://gist.github.com/Dither/6ac4720251ea7f2bb2aa9a197814e0e8)).

**Comment by hien4990** [comment]
Thank you for reply and sorry for ask unclear:
- I'm using both Chrome and Firefox mod version (which allow to add unsign extensions)
- I finded out the xpi file in https://github.com/Dither/autopatchwork-mod/releases and added to Firefox, I've already checked the Autostart extension, Enable inpage status bar (attach file) and test the addon on the sites that original Autopatchwork works but I dont see anything happen (dont see the page load and the status bar). 
Please help :(
![2017-03-29_012230](https://cloud.githubusercontent.com/assets/16345144/24420813/4b04b8c8-141e-11e7-9856-f0347d8705ed.png)

**Comment by Dither** [comment]
Ah, I see. Pack the latest version from the repository to `xpi` (better as there are some code changes too) or simply update both DB URLs to `http://wedata.net/databases/AutoPagerize/items.json` and press `Update [SITEINFO]` there were some changes in the extension since the last packed release.

**Comment by Dither** [comment]
Also consider manually set to `false`/`true` options `IGNORE_CORS: true,` and `TRY_CORRECT_LAZY: false,` in the `autopatchwork.js` file. First gives better security at the expense of pager not working on some multi-domain sites (if set to `false`) and the second tries to make the extension work with lazy-loding pages (those with images loading when you scroll to them and having placeholder instead before that). I am thinking about moving those to the properties page later.

**Comment by hien4990** [comment]
Still don't work :(

**Comment by hien4990** [comment]
Still don't work :(

**Comment by Dither** [comment]
Works for me on FF52 release with unpacked js fix though it needs to force absolute URLs.  
Try to reinstall the extension from scratch from [updated release page](https://github.com/Dither/autopatchwork-mod/releases/tag/1.10.0).

**Comment by Dither** [comment]
Works for me on FF52 release ver.  with unsigned xpi fix using js configuration, though it needs option to force absolute URLs enabled. Try to reinstall the extension from scratch from [updated release page](https://github.com/Dither/autopatchwork-mod/releases/tag/1.10.0).

**Comment by Dither** [comment]
For test page I used https://www.microsoft.com/en-US/search/GeneralInfoDrillInResults.aspx?q=Search+Microsoft

**Comment by Dither** [comment]
Just for a future reference: such behavior can be also be caused by using "database cleanup" option without first using the extension on some sites with untouched database. Cleanup removes all entries with 0 hits and that means **all** entries if you didn't use the extesnion before. (The ption is to minimize the extension's resource consumption when using it with the same set of sites.)

**Comment by Dither** [comment]
Also this, by default v1.10.0 of the extension disabled content microformats and some generic patterns in the source code because they caused more mess than solved. So it did not to work on generic forums and some sites that weren't explicitly mentioned in the database.

I planned to revert the code when publishing but probably forgot. Remembered just now while modifying other parts. 😒

**Comment by Tanookirby** [comment]
Google Searches and other sites don't seem to work in v1.10.0. Also, is the page status bar the same as the page break? If so, the page status bar check box doesn't work. Will this all be fixed in the next version?

**Comment by Dither** [comment]
>v1.10.0

What version of FF do you use? Have you used the head version or packed release? I've fixed some things in the repo that aren't in the last release. If you used head version, what is written in browser console when you enable "Debug output" and "Force absolute URLs for links in added pages" options?

> status bar the same as the page break

The status bar = green/blue/yellow/red indicator in the lower right corner that shows extension's status and gives access to its options. The option to disable it work as intended for me.

**Comment by Tanookirby** [comment]
At the moment, it will work only on developer versions of FF. The current developer version is 59. However, when I checked "Debug output" and "Force absolute URLs for links in added pages," it actually started working for google. Do you think maybe you could add an option to switch the page break on/off?

**Comment by Dither** [comment]
If you want to disable separator between pages (the thin line and `page #` text) go to SITEINFO editor and check option "noseparator" near the site/rule you want it to be disabled for.

**Comment by Dither** [comment]
The stuff with "Force absolute URLs" is mystery to me. Firefox stopped accepting some partial links in its `XMLHttpRequest` that worked fine before some point. Now it works reliably only with full URLs while Chrome and other browsers seem fine.
