### ISSUE TITLE
Site works in AutoPagerize but not correctly in AutoPatchWork Mod

### ISSUE THREAD

**Issue by whumann** [Dither/autopatchwork-mod#14]
I use AutoPatchWork Mod in Vivaldi. When I look at image galleries of stuttgarter-zeitung.de, e.g.
[Die besten Veggie-Restaurants](https://www.stuttgarter-zeitung.de/gallery.die-besten-veggi-restaurants-in-stuttgart-einmal-ohne-fleisch-bitte.98cc50d1-61bd-4df0-8de5-0f45a745a703.html)
[Lisa und Lena](https://www.stuttgarter-zeitung.de/gallery.stuttgarter-zwillinge-bei-der-bambi-verleihung-lisa-und-lena-sorgen-fuer-den-hingucker-des-abends.ed67776c-6fca-46c8-a109-a1c0e6b69d5b.html)
the images on the first two or three pages are not visible. However, this does not happen with AutoPagerize (but autopatchwork-mod is so much faster and nicer :-) and I really like it), so I expect this not to be a siteinfo problem.

**Comment by Dither** [comment]
This has to do with the site programming. It's not single images there but actually programmatically controlled image galleries. Something probably breaks the code so the galleries stop working. AutoPagerize probably makes the gallery stop working altogether by showing only first image. Try changing page `pageElemet` rule in SITEINFO editor to `//div[@class='mod-gallery']` for the similar result here.

**Comment by Dither** [comment]
This is related to the site's scripts. It's not single images there but actually programmatically controlled image galleries. Working with dynamic added content is tricky. Something probably breaks the original code's flow when adding new galleries so they stop working properly.Try changing page `pageElemet` rule in SITEINFO editor to `//div[@class='mod-gallery']` to break them altogether and show only first image.
Do all galleries work simultaneously with AutoPagerize or it breaks them the same way as above?
