### ISSUE TITLE
toggle on off on bottom panel

### ISSUE THREAD

**Issue by hien4990** [Dither/autopatchwork-mod#15]
Please make the toggle on/off in the bottom line of the bottom left panel instead of SI editor
I use it almost every site instead of SI editor and it hard to select when it easy overlap by another options.
Thanks

**Comment by Dither** [comment]
You can change this behaviour with CSS as you like to prevent inaccessible menu on your core sites, for example moving it to the center. 
Also it's easy to customize it as you like on the source-code level. Here is the fixed code at [autopatchwork.js#L765](https://github.com/Dither/autopatchwork-mod/blob/f7b751043b695b63400d3ff632d7c5b8413f8abc/includes/autopatchwork.js#L765) for the appearance you need:

```js
                bar.appendChild(img_refresh);
                if ((status.next_link || status.next_link_selector) && (status.prev_link || status.prev_link_selector))
                    bar.appendChild(reverse);
                bar.appendChild(retry);
                bar.appendChild(option);
                bar.appendChild(manager);
                bar.appendChild(onoff);
```
